Story1task1
jordanmilesbrewer/collector_app pull request #2
Opened 2024-09-23 14:15 UTC by jordanmilesbrewer

2024-09-23 14:25 UTC, ashleycoles requested changes

2024-09-23 14:25 UTC, ashleycoles commented on src/connect.php
> +function connect ()
Connect to what? Function name could be a bit better

2024-09-23 14:25 UTC, ashleycoles commented on src/mycards.php
> +    $plants = $query -> fetchALL ();
No need for the spaces ->fetchAll()

2024-09-23 14:25 UTC, ashleycoles commented on src/mycards.php
> +    $plants = $query -> fetchALL ();
Wouldn't it be a treat if you had a function that could get the data out?

2024-09-24 10:04 UTC, mallowmew commented
Database structure:
All of your fields are VARCHAR, but the data put in to growth_rate, watering_needs and fertilising_needs make me think they are actually multiple-choice. Pet-friendliness seems to be a boolean. I'd like you to take another look at your database structure and at least encode pet-friendliness as a boolean - the others there are arguable cases to change as well.

2024-09-24 10:11 UTC, mallowmew requested changes

2024-09-24 10:11 UTC, mallowmew commented on src/mycards.php
> +function pullPlantsFromDatabase($db):array
Type hints

```suggestion
function pullPlantsFromDatabase(PDO: $db): array
```

2024-09-24 10:11 UTC, mallowmew commented on src/mycards.php
> +        echo 'error';
Not sure about printing errors onto the page the user sees - simply returning no data should be enough!

2024-09-24 10:11 UTC, mallowmew commented on src/mycards.php
> +function displayPlants($plants):string
Type hinting for `$plants` parameter

2024-09-24 10:11 UTC, mallowmew commented on src/mycards.php
> +         $result .= "<h4>Name of Plant: {$plant['name']} </h4><br><p>Watering needs: {$plant['watering_needs']}</p><br><p>Growth rate: {$plant['growth_rate']}</p><br><p>Fertilising needs: Once {$plan
You could format this better

2024-09-24 10:11 UTC, mallowmew commented on tests/MycardsTest.php
> +
Don't need this extra white space.

2024-09-24 15:13 UTC, mallowmew requested changes
Database looks good now.

2024-09-25 12:48 UTC, mallowmew commented on tests/FunctionsTest.php
> +}
I don't think this is testing anything. Yes you can create 'expected' outputs that don't match when you run the function? But you don't even need to run the function to know that.

You have a success test where you put in good data and get out a good response. You should try to have a failure test (put in bad data, get out the expected response) and / or a malformed test (put in bad data, get expected response).

2024-09-26 10:06 UTC, mallowmew requested changes

2024-09-26 10:06 UTC, mallowmew commented on src/functions.php
> +        return [];
I like this - a database error doesn't need to break everything, it could be a situation where the user can just try again. Does the function that 'consumes' this array check if it is empty and display an appropriate message to the user if it is?

2024-09-26 10:06 UTC, mallowmew commented on src/functions.php
> +    }else{
```suggestion
    } else {
```

Let the `else` breathe.

2024-09-26 10:06 UTC, mallowmew commented on src/functions.php
> +        $petFriendly= 'Not pet friendly';
```suggestion
        $petFriendly = 'Not pet friendly';
```
Let the `=` breathe

2024-09-26 10:06 UTC, mallowmew commented on index.php
> +
Make your db connection here and pass it along to the plant function

2024-09-26 14:31 UTC, merged